- hosts: localhost
  become: yes
  tasks:
        - name: Build an image and push it to a private repo
          community.docker.docker_image:
              build:
                  path: "/home/pgp_project1/"
              name: docker.io/rnagar88/abctechnologies
              #tag: test
              push: true
              source: build
          register: out
        - debug:
              var: out  
        - name: start a container
          community.docker.docker_container:
             name: abc-application
             image: rnagar88/abctechnologies
             state: started
             ports:
                 - 1234:8080
             #restart: true
          register: out
        - debug:
              var: out
             #- name: Deploying to kubernetes
        - name: Create a Deployment by reading the definition from a local file 
          command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/pgp_project1/deployment.yml"    
          register: out
        - debug:
              var: out
